### ISSUE TITLE
API 28 isn't supported?

### ISSUE THREAD

**Issue by MikuDroid** [Magisk-Modules-Repo/Greenify4Magisk#10]
[magisk_install_log_20181219_044421.log](https://github.com/Magisk-Modules-Repo/Greenify4Magisk/files/2692393/magisk_install_log_20181219_044421.log)

**Comment by Progaros** [comment]
Same problem

**Comment by Darius-Hutchison** [comment]
Same with the same log.

**Comment by Abacate123** [comment]
Read [this](https://forum.xda-developers.com/showpost.php?p=78457075&postcount=1304), please.
