### ISSUE TITLE
Force close on v4.5.0

### ISSUE THREAD

**Issue by sebtech33** [Magisk-Modules-Repo/Greenify4Magisk#8]
In my app drawer it has this name "com.oasisfeng.greenify.GreenifyActivity" if i click on it it crashes instantly.
I'm on oreo.
Still got the problem on the 4.5.1 (beta) update.

**Comment by TillKruspe** [comment]
Yes, same problem here.

**Comment by SVB22** [comment]
Сonfirm problem. Oreo.

**Comment by djdeeles** [comment]
Same problem OOS Oreo

**Comment by ZeroSimple** [comment]
Same, Android 8.0.0, Sony Xperia XZ1

**Comment by Harry089** [comment]
Same here, OOS oreo. 3T

**Comment by wuliaotc** [comment]
same，oneplus 5 ,crDroid Android 9.0

**Comment by HusamG86** [comment]
Same, mi a1

**Comment by jemyzhang** [comment]
same, oneplus 4, oreo

**Comment by jemyzhang** [comment]
> same, oneplus 4, oreo

temp solution: install the apk again from /system/priv-app/Greenify/Greenify.apk

**Comment by kyelbek** [comment]
Confirming. After last module update and reboot app isn't installed properly anymore. Please roll back to previous version or fix it. Another solution for this moment is to use app systemizer.

**Comment by starcms** [comment]
Just upgrade to version 4.5.1. Problem fixed.

**Comment by SVB22** [comment]
> Just upgrade to version 4.5.1. Problem fixed.

For me, nothing has changed

**Comment by wuliaotc** [comment]
> > Just upgrade to version 4.5.1. Problem fixed.
> 
> For me, nothing has changed

also

**Comment by Abacate123** [comment]
Try to uninstall the module, and reinstall through TWRP (not the manager), this should fix this issue.
