### ISSUE TITLE
Fails to install due to maximum API 25

### ISSUE THREAD

**Issue by Dodgexander** [Magisk-Modules-Repo/Greenify4Magisk#9]
[magisk_install_log_20181207_013714.log](https://github.com/Magisk-Modules-Repo/Greenify4Magisk/files/2656121/magisk_install_log_20181207_013714.log)
Only started to happen with latest build.

**Comment by Librazy** [comment]
https://github.com/Magisk-Modules-Repo/Greenify4Magisk/commit/bc1a90b78e35e1f7f3f2343bedb91574d511210f L47？

**Comment by DevBonBon** [comment]
Fixed by e9329a6328d133936d91476aca478dcd79cb16db
